### ISSUE TITLE
Bug: Violation of unique constraints raises ForeignKeyError exception instead of IntegrityError

### ISSUE THREAD

**Issue by jt-kl** [litestar-org/advanced-alchemy#262]
### Description

When a database model contains an unique constraint attribute, any attempts to insert a duplicate value raises a ForeignKeyError exception with the message: "A foreign key is missing or invalid". I believe the correct exception should be an Integrity IntegrityError exception and if we look at the stack trace, it does show that postgresql.asyncpg raises an IntegrityError.

### MCVE

```python
from collections.abc import AsyncGenerator
from logging import DEBUG, StreamHandler, getLogger
from pathlib import Path
from typing import Any

from advanced_alchemy.base import BigIntBase
from advanced_alchemy.exceptions import IntegrityError
from advanced_alchemy.extensions.litestar import (
    AsyncSessionConfig,
    SQLAlchemyAsyncConfig,
    SQLAlchemyInitPlugin,
    async_autocommit_before_send_handler,
)
from advanced_alchemy.repository import SQLAlchemyAsyncRepository
from advanced_alchemy.service import SQLAlchemyAsyncRepositoryService
from litestar import Controller, Litestar, MediaType, Response, post
from litestar.di import Provide
from litestar.status_codes import (
    HTTP_200_OK,
    HTTP_201_CREATED,
)
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import URL, String
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

BASE_DIR = Path(__file__).parent

handler = StreamHandler()
handler.setLevel(DEBUG)

logger = getLogger(__name__)
logger.setLevel(DEBUG)
logger.addHandler(handler)
logger.propagate = False


class MyBaseDB(BigIntBase, DeclarativeBase):
    pass


class UserModel(MyBaseDB):
    __tablename__ = "users"

    email: Mapped[str] = mapped_column(String(128), index=True, unique=True)


class UserRepository(SQLAlchemyAsyncRepository[UserModel]):
    model_type = UserModel


class UserService(SQLAlchemyAsyncRepositoryService[UserModel]):
    repository_type = UserRepository

    def __init__(self, **kwargs: Any):
        self.repository: UserRepository = self.repository_type(**kwargs)
        self.model_type = self.repository.model_type


async def provide_user_svc(db_session: AsyncSession) -> AsyncGenerator[UserService, None]:
    async with UserService.new(session=db_session) as service:
        yield service


class UserSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int = Field(json_schema_extra={"example": 1})
    email: str = Field(json_schema_extra={"example": "brenda.smith@acme.com"})


class CreateUserSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    email: str = Field(json_schema_extra={"example": "brenda.smith@acme.com"})


class UserController(Controller):
    dependencies = {"user_service": Provide(provide_user_svc)}
    signature_namespace = {"UserService": UserService}
    path = "/users"

    @post(path="/", media_type=MediaType.JSON)
    async def create_item(self, user_service: UserService, data: CreateUserSchema) -> Response:  # type: ignore
        try:
            resource: UserModel = await user_service.create(data.model_dump(), auto_commit=None)

            return Response(
                content=UserSchema.model_validate(resource),
                status_code=HTTP_201_CREATED,
            )
        except IntegrityError as exc:
            logger.warning(exc)
        except Exception as exc:
            logger.warning(exc)

        return Response({"message": "Error"}, status_code=HTTP_200_OK)


session_factory = async_sessionmaker(expire_on_commit=False)
session_config = AsyncSessionConfig(expire_on_commit=False)


async def init_database_tables(app: Litestar) -> None:
    async with app.state.db_engine.begin() as connection:
        await connection.run_sync(MyBaseDB.metadata.drop_all)
        await connection.run_sync(MyBaseDB.metadata.create_all)


uri = URL.create(
    drivername="postgresql+asyncpg",
    username="app_minimal_DEV_USER",
    password="WiU5KgsL9ZwPVX2s",
    host="localhost",
    port=5432,
    database="app_minimal_DEV_DB",
)

dbsqlalchemy = SQLAlchemyAsyncConfig(
    connection_string=uri.render_as_string(False),
    session_config=session_config,
    before_send_handler=async_autocommit_before_send_handler,
)
sqlalchemy_plugin = SQLAlchemyInitPlugin(config=dbsqlalchemy)


def create_app():
    return Litestar(
        plugins=[sqlalchemy_plugin],
        on_startup=[init_database_tables],
        route_handlers=[UserController],
    )
```

### Steps to reproduce

```bash
1. Setup a Python virtual environment and PIP install the following packages: litestar[pydantic, sqlalchemy]
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Logs

```bash
Traceback (most recent call last):
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 159, in __call__
    await self.app(scope, receive, capture_response_started)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/_asgi/asgi_router.py", line 100, in __call__
    await asgi_app(scope, receive, send)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 84, in handle
    await response(scope, receive, send)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/response/base.py", line 194, in __call__
    await self.start_response(send=send)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/response/base.py", line 165, in start_response
    await send(event)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 156, in capture_response_started
    await send(event)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/app.py", line 889, in wrapped_send
    await hook(message, scope)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py", line 120, in handler
    await session.commit()
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 1009, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "ix_users_email"
DETAIL:  Key (email)=(brenda.smith@acme.com) already exists.
[SQL: INSERT INTO users (email, id) VALUES ($1::VARCHAR, nextval('users_id_seq')) RETURNING users.id]
[parameters: ('brenda.smith@acme.com',)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/app.py", line 610, in __call__
    await self.asgi_handler(scope, receive, self._wrap_send(send=send, scope=scope))  # type: ignore[arg-type]
  File "/sanitized//jt-litestar-minimal/.venv/lib/python3.10/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 162, in __call__
    raise LitestarException("Exception caught after response started") from e
litestar.exceptions.base_exceptions.LitestarException: Exception caught after response started
```

### Package Version

- advanced-alchemy     0.20.0      
- aiosqlite            0.20.0      
- alembic              1.13.3      
- annotated-types      0.7.0       
- anyio                4.6.0       
- async-timeout        4.0.3       
- asyncpg              0.29.0      
- build                1.2.2       
- certifi              2024.8.30   
- cffi                 1.17.1      
- click                8.1.7       
- cryptography         43.0.1      
- dnspython            2.6.1       
- editorconfig         0.12.4      
- email-validator      2.2.0       
- exceptiongroup       1.2.2       
- faker                30.1.0      
- fast-query-parsers   1.0.3       
- greenlet             3.1.1       
- h11                  0.14.0      
- httpcore             1.0.6       
- httptools            0.6.1       
- httpx                0.27.2      
- idna                 3.10        
- jinja2               3.1.4       
- jsbeautifier         1.15.1      
- litestar             2.12.1      
- mako                 1.3.5       
- markdown-it-py       3.0.0       
- markupsafe           2.1.5       
- mdurl                0.1.2       
- msgspec              0.18.6      
- multidict            6.1.0       
- mypy                 1.11.2      
- mypy-extensions      1.0.0       
- packaging            24.1        
- polyfactory          2.17.0      
- pycparser            2.22        
- pydantic             2.9.2       
- pydantic-core        2.23.4      
- pydantic-extra-types 2.9.0       
- pygments             2.18.0      
- pyjwt                2.9.0       
- pyproject-hooks      1.2.0       
- python-dateutil      2.9.0.post0 
- python-dotenv        1.0.1       
- pyyaml               6.0.2       
- rich                 13.9.2      
- rich-click           1.8.3       
- ruff                 0.6.9       
- semver               3.0.2       
- six                  1.16.0      
- sniffio              1.3.1       
- sqlalchemy           2.0.35      
- toml                 0.10.2      
- tomli                2.0.2       
- typing-extensions    4.12.2      
- uvicorn              0.31.0      
- uvloop               0.20.0      
- watchfiles           0.24.0      
- websockets           13.1        

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
Closed by #266
